title: Exempel
link: https://atea.se
year: 2022
customer:
  domain: atea.se
  name: Atea Sverige AB
  simple_name: Atea
  country: SE
theme: guzzle_sphinx_theme
servers:
  root_ca: 
    name: app-RootCA
    ip: 192.168.56.100
    os: Windows Server 2022
  issuing_ca:
    name: app-IssuingCA
    ip: 192.168.56.101
    os: Windows Server 2022
  repository:
    name: app-Repository
    ip: 192.168.56.102
    os: Windows Server 2022
accounts:
  domain: 
    user: foo.foobarsson
  local: 
    user: Administrator
location:
  log: C:\Log
  database: C:\Database
templates:
  - from: Computer
    name: Atea Computer
    validity: 365
    renewal_period: 90
    publish: Yes
    use_ec: Yes
    group: Domain Computers
    subject:
      email: Yes
      dnsname: Yes
      upn: Yes