title: Exempel
link: https://atea.se
year: 2022
classification: Konfidentiell
customer:
  domain: atea.se
  name: Atea Sverige AB
  simple_name: Atea
  country: SE
  # Possible choices are:
  #  - RSA4096
  #  - P256
  key_specification: P256
theme: guzzle_sphinx_theme
extras:
#  naming_and_profile_document:
servers:
  root_ca:
    name: app-RootCA
    ip: 192.168.56.100
    os: Windows Server 2022
  issuing_ca:
    name: app-IssuingCA
    ip: 192.168.56.101
    os: Windows Server 2022
  repositories:
    - name: app-Repository
      ip: 192.168.56.102
      os: Windows Server 2022
accounts:
  domain:
    user: foo.foobarsson
  local:
    user: Administrator
location:
  log: C:\Log
  database: C:\Database
network:
  dcom_port: 4000
templates:
  - from: Computer
    name: Atea Computer
    description: Certificate for workstations in the domain.
    validity: 365
    renewal_period: 90
    publish: No
    use_ec: Yes
    groups:
      - name: Domain Computers
        autoenroll: Yes
    subject:
      email: No
      dnsname: Yes
      upn: No
  - from: User
    name: Atea User
    description: Certificate for users in the domain.
    validity: 365
    renewal_period: 90
    publish: Yes
    use_ec: Yes
    groups:
      - name: Domain Users
        autoenroll: Yes
    subject:
      email: Yes
      dnsname: No
      upn: Yes