title: Active Directory Certificate Services
link: https://atea.se
year: 2022
theme: guzzle_sphinx_theme
classification: Konfidentiell
#system_description: Provide X.509 certificates for Windows workstations and employees at Atea.
consultant:
  name: Foo Foobarsson
  company: Atea Sverige AB
owner:
  name: Foo Foobarsson
  company: Atea Managed Services
customer:
  domain: atea.se
  name: Atea Sverige AB
  simple_name: Atea
  country: SE
extras:
  naming_and_profile_document:
servers:
  root_ca:
    name: app-RootCA
    ip: 192.168.56.100
    vlan: VLAN0
    netmask: 255.255.255.0
    gateway: 192.168.56.1
    os: Windows Server 2022
    location:
      log: C:\Log
      database: C:\Database
    policy:
      high_serial: 0xFFFFFFFF
      keep_expired_certificates_on_crl: No
      # Possible choices are:
      #  - RSA4096
      #  - P256
      key_specification: P256
      key_storage_provider: Microsoft Software Key Storage Provider
  issuing_ca:
    name: app-IssuingCA
    ip: 192.168.56.101
    vlan: VLAN0
    netmask: 255.255.255.0
    gateway: 192.168.56.1
    os: Windows Server 2022
    dcom_port: 4000
    location:
      log: C:\Log
      database: C:\Database
    policy:
      high_serial: 0xFFFFFFFF
      keep_expired_certificates_on_crl: No
      # Possible choices are:
      #  - RSA4096
      #  - P256
      key_specification: P256
      key_storage_provider: Microsoft Software Key Storage Provider
  repositories:
    - name: app-Repository
      ip: 192.168.56.102
      vlan: VLAN1
      netmask: 255.255.255.0
      gateway: 192.168.56.1
      os: Windows Server 2022
  dns_servers:
    - 192.168.56.10
    - 192.168.56.11
  domain_controllers:
    - name: app-DC
      ip: 192.168.56.1
accounts:
  domain:
    user: foo.foobarsson
  local:
    user: Administrator
templates:
  - from: Computer
    name: Atea Computer
    description: Certificate for workstations in the domain.
    validity: 365
    renewal_period: 90
    publish: No
    use_ec: Yes
    groups:
      - name: Domain Computers
        autoenroll: Yes
    subject:
      email: No
      dnsname: Yes
      upn: No
  - from: User
    name: Atea User
    description: Certificate for users in the domain.
    validity: 365
    renewal_period: 90
    publish: Yes
    use_ec: Yes
    groups:
      - name: Domain Users
        autoenroll: Yes
    subject:
      email: Yes
      dnsname: No
      upn: Yes