RUN apt install -y texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra latexmk texlive-luatex graphviz cowsay && \
    pip3 install sphinx ansible restructuredtext-lint doc8 diagrams docxbuilder guzzle_sphinx_theme docxtpl && \
    ansible-galaxy collection install community.general
