- name: Build ADCS documentation
  hosts: localhost
  gather_facts: False
  pre_tasks:
    - name: Check if the Naming and Profile Document can be generated
      stat:
        path: files/naming_document
      register: naming_document_data
  tasks:
    - block:
      - name: Create Naming and Profile Document
        include_role:
          name: naming_document
        when: naming_document_data.stat.exists
      - name: Create installation manual
        include_role:
          name: installation_manual
      - name: Create operations manual
        include_role:
          name: operations_manual
      rescue:
        - name: Cleaning up
          file:
            path: '{{ docs }}'
            state: absent
          with_items:
            - roles/installation_manual/_docs
            - roles/operations_manual/_docs