- name: Build ADCS documentation
  hosts: localhost
  gather_facts: False
  pre_tasks:
    - name: Check if the Naming and Profile Document can be generated
      stat:
        path: files/naming_document
      register: naming_document_data
  roles:
    - role: naming_document
      when: naming_document_data.stat.exists
    - role: system_documentation