name: Ansible Linting
on:
- push
- pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Perform linting
        uses: ansible-community/ansible-lint-action@main
