name: Publish
on:
  push:
    branches:
      - 'main'
jobs:
  publish-container:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '#nobuild') }}
    steps:
    - name: Checkout the code from GitHub
      uses: actions/checkout@v3
    - name: Build the container image
      run: |
        ./build.sh && \
        docker tag $(docker images -q realiserad/adcs-deployment) ghcr.io/realiserad/adcs-deployment
    - name: Run the container with the sample configuration
      run: |
        docker run \
          -v $(pwd)/group_vars/all.yml:/build/all.yml \
          -v $(pwd)/files:/build/files \
          -v /tmp/release:/build/release \
          ghcr.io/realiserad/adcs-deployment
    - name: Log in to the GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push the container to ghcr.io
      run: |
        docker push ghcr.io/realiserad/adcs-deployment
