name: Test the container
on:
  pull_request:
    branches:
      - 'main'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code from GitHub
      uses: actions/checkout@v3
    - name: Build the container image
      run: ./build.sh
    - name: Run the container with the sample configuration
      run: |
        docker run \
          -v $(pwd)/group_vars/all.yml:/build/all.yml \
          -v $(pwd)/files:/build/files \
          -v /tmp/release:/build/release \
          realiserad/adcs-deployment
    - name: Ensure artefacts are created
      shell: bash
      run: |
        test -f "/tmp/release/naming-document.pdf"
        test -f "/tmp/release/operations-manual.zip" 
        test -f "/tmp/release/installation-manual.zip"

